// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQv9YckEMYLJop0m-BcdCiTPFFYMxZa4',
    appId: '1:502537194817:web:cb57be2dea05962b0525c0',
    messagingSenderId: '502537194817',
    projectId: 'peswoes',
    authDomain: 'peswoes.firebaseapp.com',
    storageBucket: 'peswoes.appspot.com',
    measurementId: 'G-TEDFP5PW7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPoA7R2vLqeUYt8TXNq6BNG9IqJjTIJA8',
    appId: '1:502537194817:android:77d8eb90af36151c0525c0',
    messagingSenderId: '502537194817',
    projectId: 'peswoes',
    storageBucket: 'peswoes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBTPMU36hCYQaTz6HsXIIn29_w3ju6CUA',
    appId: '1:502537194817:ios:5424c9a4bc28fff60525c0',
    messagingSenderId: '502537194817',
    projectId: 'peswoes',
    storageBucket: 'peswoes.appspot.com',
    androidClientId: '502537194817-sp9p46hd99cok2nlhvlrkj81955fa9mr.apps.googleusercontent.com',
    iosClientId: '502537194817-f3dsa5mpe8qg5a078g422ao1go8tibbp.apps.googleusercontent.com',
    iosBundleId: 'com.university.canteens.collegeCanteens',
  );
}
